name: Run Tests

on:
  push:
    branches:
      - master
      - v1
  pull_request:
    branches:
      - master
      - v1

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.13, 1.14, 1.15]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Set GOPATH, PATH and ENV
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "GOPROXY=https://proxy.golang.org" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: |
          mkdir -p $GOPATH/bin
          curl -L -o $GOPATH/bin/gfmrun "https://github.com/urfave/gfmrun/releases/download/v1.2.14/gfmrun-$(go env GOOS)-amd64-v1.2.14"
          chmod +x $GOPATH/bin/gfmrun
          npm install -g markdown-toc@1.2.0

      - name: Run Tests (v1)
        run: |
          go run build.go vet
          go run build.go test
          go run build.go gfmrun docs/v1/manual.md
          go run build.go toc docs/v1/manual.md
